# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

params:
  seed: 42
  env:
    clip_observations: 5.0
    clip_actions: 1.0
  algo:
    name: a2c_continuous
  model:
    name: continuous_a2c_logstd
  network:
    name: actor_critic
    separate: false
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: true
    cnn:
      type: conv2d
      activation: relu
      initializer:
        name: default
      regularizer:
        name: None
      convs:
      - filters: 17
        kernel_size: 6
        strides: 4
        padding: 0
    mlp:
      units:
      - 12
      activation: elu
      initializer:
        name: default
  load_checkpoint: false
  load_path: ''
  config:
    name: ar4_kine_mp_camera
    env_name: rlgpu
    device: cuda:0
    device_name: cuda:0
    multi_gpu: false
    ppo: true
    mixed_precision: false
    normalize_input: false
    normalize_value: true
    num_actors: -1
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: true
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: 200
    save_best_after: 50
    save_frequency: 25
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: true
    e_clip: 0.2
    horizon_length: 64
    minibatch_size: 128
    mini_epochs: 4
    critic_coef: 2
    clip_value: true
    seq_length: 4
    bounds_loss_coef: 0.0001
    